export const UPDATE_QUERY_STRING = 'UPDATE_QUERY_STRING';

export const SEARCH_REPOS_START = 'SEARCH_REPOS_START ';
export const SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS';
export const SEARCH_REPOS_FAIL = 'SEARCH_REPOS_FAIL';

export const CLEAR_RESULT = 'CLEAR_RESULT';

