export const FETCH_WATCH_REPOS_START = 'FETCH_WATCH_REPOS_START';
export const FETCH_WATCH_REPOS_SUCCESS = 'FETCH_WATCH_REPOS_SUCCESS';
export const FETCH_WATCH_REPOS_FAIL = 'FETCH_WATCH_REPOS_FAIL';

export const SUBSCRIBE_REPO_START = 'SUBSCRIBE_REPO_START';
export const SUBSCRIBE_REPO_SUCCESS = 'SUBSCRIBE_REPO_SUCCESS';
export const SUBSCRIBE_REPO_FAIL = 'SUBSCRIBE_REPO_FAIL';

